### Author : BootLabsTech Pvt Ltd.
### Description: Schema YAML file for GKE Cluster Creation

# This should match the release tag
publishedVersion: '0.1.1'
publishedVersionMetadata:
  releaseNote: >-
    Initial release.
    # releaseTypes list is optional.
    # an existing vulnerability
    releaseTypes:
    - Feature
    - BugFix
    - Upgrade
    # If "recommended" is "true", users using older releases are encouraged
    # to update as soon as possible. This is useful if, for example, this release
    # fixes a critical issue.
    recommended: true

properties:
  name:
    inputType: textfield
    type: string # UI should render a text box
    description: Specifies the name of the Container Registry. Only Alphanumeric characters allowed
    title: "ACR Name" # label in UI
    required: true # mandatory valu
  sku:
    inputType: select
    type: string # UI should render a text box
    description: The SKU name of the container registry. Possible values are Basic, Standard and Premium
    title: "ACR SKU" # label in UI
    required: true # mandatory valu
    options:
      - Basic
      - Standard
      - Premium